global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus tự monitor
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Process Exporter
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node Exporter (optional - để monitor hệ thống)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
